/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnerOverviewRouteImport } from './routes/partner.overview'
import { Route as AppSaveRouteImport } from './routes/app.save'
import { Route as AppProjectionRouteImport } from './routes/app.projection'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppActivityRouteImport } from './routes/app.activity'

const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerOverviewRoute = PartnerOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => PartnerRoute,
} as any)
const AppSaveRoute = AppSaveRouteImport.update({
  id: '/save',
  path: '/save',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectionRoute = AppProjectionRouteImport.update({
  id: '/projection',
  path: '/projection',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/partner': typeof PartnerRouteWithChildren
  '/app/activity': typeof AppActivityRoute
  '/app/home': typeof AppHomeRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/projection': typeof AppProjectionRoute
  '/app/save': typeof AppSaveRoute
  '/partner/overview': typeof PartnerOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/partner': typeof PartnerRouteWithChildren
  '/app/activity': typeof AppActivityRoute
  '/app/home': typeof AppHomeRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/projection': typeof AppProjectionRoute
  '/app/save': typeof AppSaveRoute
  '/partner/overview': typeof PartnerOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/partner': typeof PartnerRouteWithChildren
  '/app/activity': typeof AppActivityRoute
  '/app/home': typeof AppHomeRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/projection': typeof AppProjectionRoute
  '/app/save': typeof AppSaveRoute
  '/partner/overview': typeof PartnerOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/partner'
    | '/app/activity'
    | '/app/home'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/projection'
    | '/app/save'
    | '/partner/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/partner'
    | '/app/activity'
    | '/app/home'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/projection'
    | '/app/save'
    | '/partner/overview'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/partner'
    | '/app/activity'
    | '/app/home'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/projection'
    | '/app/save'
    | '/partner/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PartnerRoute: typeof PartnerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/overview': {
      id: '/partner/overview'
      path: '/overview'
      fullPath: '/partner/overview'
      preLoaderRoute: typeof PartnerOverviewRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/app/save': {
      id: '/app/save'
      path: '/save'
      fullPath: '/app/save'
      preLoaderRoute: typeof AppSaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projection': {
      id: '/app/projection'
      path: '/projection'
      fullPath: '/app/projection'
      preLoaderRoute: typeof AppProjectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppHomeRoute: typeof AppHomeRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProjectionRoute: typeof AppProjectionRoute
  AppSaveRoute: typeof AppSaveRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppHomeRoute: AppHomeRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProfileRoute: AppProfileRoute,
  AppProjectionRoute: AppProjectionRoute,
  AppSaveRoute: AppSaveRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PartnerRouteChildren {
  PartnerOverviewRoute: typeof PartnerOverviewRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerOverviewRoute: PartnerOverviewRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PartnerRoute: PartnerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
